# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7864ba5b8868461417713e57fabf8a62ae979b0450892107b947ccc24f00a9582c3bd4b31426d6fab714ae5cfba751c615e0069de79d652de14c55f8b0e033e3

test:
  secret_key_base: 0a516047ae123b1065024cd5f52a04ef333274412bc0b92755b24992809a553642be6969e053e4c68244e52415aeceb60e2b13452ccf292ddd7957e85ade862c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
